create DATABASE PROYECTOGIMNASIO

create TABLE USUARIOS
(
CODIGO INT IDENTITY (1,1),
CORREO VARCHAR(50),
CLAVE VARCHAR (50) NOT NULL,
NOMBRE VARCHAR (50) NOT NULL,
CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO),
CONSTRAINT UQ_UNIQUE UNIQUE(CORREO)
)

select * from usuarios
INSERT USUARIOS VALUES ('allan@upi.com','123', 'Allan')

CREATE TABLE CLIENTES
(
CODIGO INT identity (1,1),
NOMBRE VARCHAR(50) NOT NULL,
APELLIDO VARCHAR (50) NULL,
TELEFONO VARCHAR (15) NULL,
USUARIO INT,
CONSTRAINT PK_CODIGOCLIENTE PRIMARY KEY (CODIGO),
CONSTRAINT PK_USUARIO1 FOREIGN KEY (USUARIO) REFERENCES  USUARIOS (CODIGO)
)

insert into clientes values ('allan','morales', '2345678',1),
('RAQUEL','morales', '7643421',1)
select * from clientes

CREATE TABLE PRODUCTO 
(
CODIGO INT identity (1,1),
NOMBRE VARCHAR(50) NOT NULL,
PRECIO MONEY DEFAULT 0,
CONSTRAINT PK_CODIGOPRODUCTO PRIMARY KEY (CODIGO)
)
INSERT INTO PRODUCTO VALUES ('BOTELLA AGUA', 500),('CAMISAS', 3000),('COMPUTADORAS', 6000)
SELECT * FROM PRODUCTO

CREATE TABLE PROVINCIA
(
CODIGO INT IDENTITY (1,1),
NOMBRE VARCHAR(50) NOT NULL,
CONSTRAINT PK_CODIGOPROVINCIA PRIMARY KEY (CODIGO)
)
INSERT INTO PROVINCIA VALUES ('SAN JOSE'),('GUANACASTE'),('ALAJUELA'),
('HEREDIA'),('LIMON'),('PUNTARENAS'), ('CARTAGO')
SELECT * FROM PROVINCIA

CREATE TABLE CANTON
(
CODIGO INT IDENTITY (1,1),
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_PROVINCIA INT,
CONSTRAINT PK_CODIGOCANTON PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO)
)
INSERT INTO CANTON ( NOMBRE) VALUES ( 'CANTON 1'), ('CANTON 2'), ('CANTON 3')
 select * from canton

CREATE TABLE DISTRITO
(
CODIGO INT IDENTITY (1,1),
NOMBRE VARCHAR(50) NOT NULL,
CODIGO_CANTON INT,
CONSTRAINT PK_CODIGODISTRITO PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCANTON FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO)
)
INSERT INTO Distrito values ('distrito 1',1), ('DISTRITO 2',1),('DISTRITO 3',1)
select * from distrito

CREATE TABLE DIRECCIONES
(
CODIGO INT IDENTITY (1,1),
CODIGO_CLIENTE INT,
CODIGO_PROVINCIA INT,
CODIGO_CANTON INT,
CODIGO_DISTRITO INT,
CONSTRAINT PK_CODIGODIRECCIONES PRIMARY KEY (CODIGO),
CONSTRAINT FK_CODIGOCLIENTES FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO),
CONSTRAINT FK_CODIGOPROVINCIA1 FOREIGN KEY (CODIGO_PROVINCIA) REFERENCES PROVINCIA(CODIGO),
CONSTRAINT FK_CODIGOCANTON1 FOREIGN KEY (CODIGO_CANTON) REFERENCES CANTON(CODIGO),
CONSTRAINT FK_CODIGODISTRITO FOREIGN KEY (CODIGO_DISTRITO) REFERENCES DISTRITO(CODIGO)
)

CREATE TABLE MAE_FACTURA
(
NFACTURA INT IDENTITY (1,1),
FECHA DATETIME,
CODIGO_CLIENTE INT,
TOTAL MONEY,
CONSTRAINT PK_NFACTURA PRIMARY KEY (NFACTURA),
CONSTRAINT FK_CODIGOCLIENTE2 FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTES(CODIGO)
)

CREATE TABLE DET_FACTURA
(
CODIGO INT IDENTITY (1,1),
NFACTURA INT,
CODIGO_PRODUCTO INT,
CANTIDAD INT,
PRECIO MONEY,
CONSTRAINT PK_CODIGODETFACTURA PRIMARY KEY (CODIGO),
CONSTRAINT FK_NFACTURA FOREIGN KEY (NFACTURA) REFERENCES MAE_FACTURA(NFACTURA),
CONSTRAINT FK_CODIGOPRODUCTO1 FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO (CODIGO)
)
